version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - app_network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   ports:
  #     - "7777:7777"
  #   expose:
  #     - "7777"
  #   restart: unless-stopped
  #   networks:
  #     - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    # volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      # - backend
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - app_network

networks:
  app_network:
    driver: bridge